[profile.default]
src = "contracts"
out = "out"
scripts = "script"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc = "0.8.17"
#evm_version = "shanghai"
remappings = [
  "@openzeppelin/contracts=lib/OpenZeppelin/openzeppelin-contracts@4.8.3/contracts",
  "@openzeppelin/contracts-upgradeable=lib/OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.3/contracts",
  "solidity-bytes-utils/contracts=lib/GNSPS/solidity-bytes-utils@0.8.0/contracts"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
