[profile.default]
src = "contracts"
out = "out"
scripts = "fscripts"
test = "ftests"
libs = ["libs"]
optimizer = true
optimizer_runs = 200
solc = "0.8.9"
#evm_version = "shanghai"
remappings = [
  "@openzeppelin/contracts=libs/OpenZeppelin/openzeppelin-contracts@4.8.0/contracts",
  "@openzeppelin/contracts-upgradeable=libs/OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.0/contracts",
  "solidity-bytes-utils/contracts=libs/GNSPS/solidity-bytes-utils@0.8.0/contracts"
]
